### ISSUE TITLE
Support httpx 0.24.0

### ISSUE THREAD

**Issue by JacobHenner** [pythongssapi/httpx-gssapi#27]
httpx 0.24.0 [was released](https://github.com/encode/httpx/releases/tag/0.24.0) at the beginning of April, but this library is marked as compatible with `httpx>=0.16,<0.24`. Please extend compatibility to include 0.24.0.

**Comment by aiudirog** [comment]
Thanks for the reminder, I will have the release out shortly.

**Comment by aiudirog** [comment]
Fixed in [v0.2](https://github.com/pythongssapi/httpx-gssapi/releases/tag/v0.2)

I also dropped support for 3.6, as it was was no longer supported in the ubuntu-latest runner and hasn't been officially supported for while. If this is a problem, please let me know and I can put it in the work for supporting it longer term.
